version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    container_name: connectagro-db
    environment:
      MARIADB_ROOT_PASSWORD: 'root_password'
      MARIADB_DATABASE: 'connect_agro_db'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: