name: connect_agro_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  mysql1: ^0.20.0
  shelf_cors_headers: ^0.1.5


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
